# Generated by Django 3.1.1 on 2021-01-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryset_reporter', '0004_auto_20200330_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayfield',
            name='distinct',
            field=models.BooleanField(default=False),
        ),
    ]
